steps:
  # Build the frontend image using the fixed Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lingua-phone/lingua-frontend:latest', '-f', 'docker/frontend.Dockerfile', '.']
  
  # Push the frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lingua-phone/lingua-frontend:latest']

images:
  - 'gcr.io/lingua-phone/lingua-frontend:latest'