version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - USE_GCP=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service-account.json
      - GOOGLE_CLOUD_PROJECT=lingua-phone
    env_file:
      - .env
    volumes:
      - ./packages/backend/keys:/app/keys:ro  # Mount keys directory
